### ISSUE TITLE
[task] client / feature / main page / findYourWines

### ISSUE THREAD

**Issue by GriGni** [codestates/Buenos_vinos_client#11]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: find some wines chosen some char by a client. 

### TODO
1. [x] css 그리고 레이아웃
2. [x] 캐러셀 구현 또는 페이지네이션
3. [x] DB에서 와인 데이터 받아오기

### Labels
- Estimated time: `E: 6h`
- Group : `client`
- Sprint:
- Urgency: `High`
